name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
            archive: zip
          - os: windows-latest
            arch: aarch64
            target: aarch64-pc-windows-msvc
            archive: zip
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
            archive: zip

    steps:
      - uses: actions/checkout@v4
      
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: clip-${{ matrix.target }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clip-${{ matrix.target }}
          path: |
            clip-${{ matrix.target }}.*
            clip-${{ matrix.target }}